version: '3'
services:
  app:
    image: node:19
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development

